// <auto-generated />
using System;
using Carnation.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Carnation.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Carnation.Models.Product", b =>
                {
                    b.Property<Guid>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PPrice")
                        .HasColumnType("float");

                    b.Property<string>("PQuality")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PId");

                    b.ToTable("Product_Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
